# Filename: my.kv

<MyGrid>:
    GridLayout:
        cols:1
        size:root.width, root.height
        
        Image:
            source: 'outputpic.jpg'
            
        GridLayout:
            cols:2
            
            Label:
                text: "Deflection: "
                
            Label:
                text: "Angle A: "

                
            
                
            