
WindowManager:
    Connection_Window:
    Variables_Window:
    Output_Window:

<Output_Window>: 
    FloatLayout:
        Button:


        TextInput:
        
        Label:


        Image: 


<SampleWindow>:

    FloatLayout:
        
        Button:

        TextInput:

        Label:

        Image:

<MyPopup>:
    
    TabbedPanel: (Material tabs)
        
    Carousel: (Material information sliders)
            





